name: relayctl
version: 0.0.0.0
synopsis: Control my relays
description: Control my relays
github: vkleen/relayctl
category: Utility

_common: !include "./common.yaml"
<<: *legal
<<: *default-ghc-options
<<: *relude

library:
  source-dirs: spidev

  dependencies:
    - bytestring
    - finite-typelits
    - inline-c
    - unix
    - vector
    - vector-sized

executables:
  relayd:
    <<: *default-exe-options
    main: Main.hs
    source-dirs: relayd
