name: relayctl
version: 0.0.0.0
synopsis: Control my relays
description: Control my relays
github: vkleen/relayctl
category: Utility

license: BSD-3-Clause
author: Viktor Kleen
maintainer: viktor@kleen.org
copyright: 2020 Viktor Kleen

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wmissing-export-lists
  - -Wno-missing-methods
  - -Wno-type-defaults
default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NoMonomorphismRestriction
  - NoStarIsType
  - OverloadedLabels
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances

dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude)
      - (Relude.Unsafe as Unsafe)

_default-exe-options: &default-exe-options
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

library:
  source-dirs: relay-api

  dependencies:
    - aeson
    - finite-typelits
    - vector-sized
    - generic-lens
    - lens
    - servant
    - text
    - time
    - unix
    - vector

executables:
  relayd:
    <<: *default-exe-options
    main: Main.hs
    source-dirs: relayd
    dependencies:
      - relayctl
      - servant
      - finite-typelits
      - servant-server
      - fixed-vector
      - warp
      - containers
      - stm
      - spidev
      - unix
      - lens
      - generic-lens
      - async
      - fast-logger
      - safe-exceptions
      - stm-delay
      - text
      - vector-sized
      - network
      - wai
      - bytestring
      - net-mqtt
      - dns
      - dlist
      - aeson
      - aeson-pretty
      - network-uri
      - tls
      - connection
      - data-default-class
      - base64-bytestring
      - x509-validation
  relayctl:
    <<: *default-exe-options
    main: Main.hs
    source-dirs: relayctl
    dependencies:
      - relayctl
      - servant
      - servant-client
      - servant-client-core
      - http-client
      - aeson
      - optparse-applicative
      - optparse-generic
      - containers
      - text
      - ansi-wl-pprint
      - vector-sized
      - unix
      - network
      - bytestring
